version: "3"


services:
 nginx:
   build: ./nginx
 
   container_name: nginx
   networks: 
    darkn:
      ipv4_address: 172.20.0.2
   volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
     - ./nginx/ssl:/etc/nginx/ssl
     - ./flask/app/static:/usr/share/nginx/html/static

   ports:
     - 81:81
     - 443:443 
 web:
   build: ./flask
   container_name: flaskConcurso
   networks:
     darkn:
       ipv4_address: 172.20.0.3
   volumes: 
     - ./flask:/usr/home/flask
   ports:
     - 8000:8000
     - 8080:8080
     - 5000:5000

networks:
  darkn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16 
